services:
  rails_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10524:10524"
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/rails
      - ./config/master.key:/rails/config/master.key:ro
    networks:
      - app-network

  nextjs_app:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "10222:10222"
    environment:
      NODE_ENV: production
      PORT: 10222
      API_URL: http://rails_app:10524
    networks:
      - app-network
    depends_on:
      - rails_app

networks:
  app-network:
    driver: bridge